services:
  watchducker:
    image: ghcr.io/ximilalaxiang/watchducker:latest
    container_name: watchducker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - watchducker_data:/data
    ports:
      - "8072:8080"
    environment:
      - TZ=Asia/Shanghai
      - WATCHDUCKER_ALL=true
      - WATCHDUCKER_CRON=0 2 * * *
      - WATCHDUCKER_CLEAN=true
      - WATCHDUCKER_WEB_PORT=8080
      - WATCHDUCKER_DATA_DIR=/data
      # - WATCHDUCKER_SETTING_PUSH_SERVER=telegram
      # - WATCHDUCKER_TELEGRAM_API_URL=api.telegram.org
      # - WATCHDUCKER_TELEGRAM_BOT_TOKEN=your_bot_token
      # - WATCHDUCKER_TELEGRAM_CHAT_ID=your_chat_id

volumes:
  watchducker_data:
